#!/bin/python3

import sys

def bombyx2(n, i0, i1) -> int:
    try:
        if (i1 < i0 or i1 < 0 or i0 < 0):
            return 84
        growth_rate = 1.0
        while growth_rate < 4.0:
            stop = 1
            result = float(n)
            while stop < i0:
                result = growth_rate * result * ((1000 - result) / 1000)
                stop += 1
            while stop <= i1:
                print(f"{growth_rate:.2f} {result:.2f}")
                result = growth_rate * result * ((1000 - result) / 1000)
                stop += 1
            growth_rate += 0.01
        return 0
    except:
        return 84


def bombyx1(n, k) -> int:
    try:
        if k < 1 or k > 4:
            return 84
        for i in range(1, 101):
            print(f"{i} {n:.2f}")
            n = k * n * (1000 - n) / 1000
        return 0
    except:
        return 84;

def help_menu():
    print(
"""USAGE
    ./106bombyx n [k | i0 i1]
DESCRIPTION
    n number of first generation individuals
    k growth rate from 1 to 4
    i0 initial generation (included)
    i1 final generation (included)""")

def main() -> int:
    try:
        if len(sys.argv) == 3:
            return bombyx1(int(sys.argv[1]), float(sys.argv[2]))
        elif len(sys.argv) == 4:
            return bombyx2(int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3]))
        else:
            help_menu()
            return 84;
    except:
        return 84

if __name__ == "__main__":
    if main() == 0:
        sys.exit(0);
    else:
        sys.exit(84)
